[package]
name = "a2d-ffi"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lib]
crate-type = ["lib", "cdylib"]

[lints]
workspace = true

[[bin]]
name = "uniffi-bindgen"
path = "src/bin/uniffi-bindgen.rs"

[dependencies]
a2d-core = { path = "../a2d-core" }
a2d-domain = { path = "../a2d-domain" }
a2d-identity = { path = "../a2d-identity" }
uniffi = { version = "0.32", features = ["cli"] }
