#!/usr/bin/env bash
# Regenerates Kotlin and Swift UniFFI bindings for a2d-ffi.
#
# Output is NOT committed -- these are build artifacts, regenerated by Android/Xcode builds (and
# eventually CI, TODO 1.3/2.4). This script exists so a developer (or CI) can regenerate them the
# same way crates/a2d-ffi/tests/binding_generation.rs does, without re-deriving the command.
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

cargo build -p a2d-ffi --lib

case "$(uname -s)" in
  Darwin) LIB="target/debug/liba2d_ffi.dylib" ;;
  Linux)  LIB="target/debug/liba2d_ffi.so" ;;
  *)      LIB="target/debug/a2d_ffi.dll" ;;
esac

OUT_DIR="${1:-target/bindings}"
rm -rf "$OUT_DIR"

cargo run -p a2d-ffi --bin uniffi-bindgen -- generate --library "$LIB" --language kotlin --out-dir "$OUT_DIR/kotlin"
cargo run -p a2d-ffi --bin uniffi-bindgen -- generate --library "$LIB" --language swift --out-dir "$OUT_DIR/swift"

echo "Bindings generated under $OUT_DIR"
